#!/bin/sh

function usage {
    cat <<EOM
Usage: $(basename "$0") [OPTION]...
    -h          Display help
    -t VALUE    Set taeget
EOM

    exit 2
}

while getopts t:h OPT; do
    case $OPT in
        t )
            TO="${OPTARG}"
            ;;
        h | '--help' | * )
            usage
            ;;
    esac
done

echo "python hoge.py ${@:$#:1} ${TO}"